//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_mixedRealityRecorder : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean OperatorToggleRecording
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorToggleRecording;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorPointerMode
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorPointerMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorLightMode
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorLightMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorWebcamMode
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorWebcamMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorTrigger
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserTrigger
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserSwitchPrompterPosition
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserSwitchPrompterPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserNextPrompterPage
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserNextPrompterPage;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserPointerMode
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserPointerMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserMarkerMode
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserMarkerMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserPrompterMode
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserPrompterMode;
            }
        }
    }
}
