//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_mixedRealityRecorder : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean OperatorToggleRecording
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorToggleRecording;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorTrigger
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserTrigger
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserNextPrompterPage
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserNextPrompterPage;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorRotateScene
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorRotateScene;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorCycleMode
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorCycleMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserCycleMode
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserCycleMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorDPadUp
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorDPadUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorDPadDown
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorDPadDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorDPadRight
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorDPadRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean OperatorDPadLeft
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_OperatorDPadLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserDPadUp
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserDPadUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserDPadDown
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserDPadDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserDPadRight
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserDPadRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserDPadLeft
        {
            get
            {
                return SteamVR_Actions.mixedRealityRecorder_UserDPadLeft;
            }
        }
    }
}
